// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lgstierfmiezdeqhwyap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxnc3RpZXJmbWllemRlcWh3eWFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MTQzMzgsImV4cCI6MjA3MDA5MDMzOH0.4yIqlsfe9N7glx8B2csBv1u9GdwOz1Ob4rLZQQa5ihM";

// Custom storage adapter that delegates to localStorage or sessionStorage
// based on the user's "Remember Me" preference.
const REMEMBER_ME_KEY = "mibuks_remember_me";

function getActiveStorage(): Storage {
  const remember = localStorage.getItem(REMEMBER_ME_KEY);
  return remember === "false" ? sessionStorage : localStorage;
}

export function setRememberMe(value: boolean) {
  if (value) {
    localStorage.setItem(REMEMBER_ME_KEY, "true");
  } else {
    localStorage.setItem(REMEMBER_ME_KEY, "false");
  }
}

const adaptiveStorage = {
  getItem: (key: string) => {
    return getActiveStorage().getItem(key);
  },
  setItem: (key: string, value: string) => {
    getActiveStorage().setItem(key, value);
  },
  removeItem: (key: string) => {
    // Clean from both to prevent stale sessions
    localStorage.removeItem(key);
    sessionStorage.removeItem(key);
  },
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: adaptiveStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
